#%RAML 1.0 NamedExample
example:
  Id : 1
  insurerName : Jhon
  emailid : abd@gmail.com
  phonenumber: 78786767
  dob : 19-Nov-1997
  address: Rue Millois, India
  InsurancePeriod : 1 year
  SumInsured: 500000
  PremiumAmount: 400